name: Esteira de Integração Contínua

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline-qualidade:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Atualizado de '18' para '22' (ou '24')


      - name: Instalar Dependências
        run: npm install

      - name: Executar Testes Unitários
        run: npm test -- --watchAll=false

      - name: Compilar Projeto (Build)
        run: npm run build
